import os
import time
os.mkdir("_exe_")
os.mkdir("data")
os.mkdir("build")

def info() :
    ROOT_DIR = os.path.abspath(os.curdir)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(/)", end = "\r")
    time.sleep(0.1)
    print("loading(-)", end = "\r")
    time.sleep(0.1)
    print("loading(\)", end = "\r")
    time.sleep(0.1)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(/)", end = "\r")
    time.sleep(0.1)
    print("loading(-)", end = "\r")
    time.sleep(0.1)
    print("loading(\)", end = "\r")
    time.sleep(0.1)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(/)", end = "\r")
    time.sleep(0.1)
    print("loading(-)", end = "\r")
    time.sleep(0.1)
    print("loading(\)", end = "\r")
    time.sleep(0.1)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(/)", end = "\r")
    time.sleep(0.1)
    print("loading(-)", end = "\r")
    time.sleep(0.1)
    print("loading(\)", end = "\r")
    time.sleep(0.1)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(/)", end = "\r")
    time.sleep(0.1)
    print("loading(-)", end = "\r")
    time.sleep(0.1)
    print("loading(\)", end = "\r")
    time.sleep(0.1)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(/)", end = "\r")
    time.sleep(0.1)
    print("loading(-)", end = "\r")
    time.sleep(0.1)
    print("loading(\)", end = "\r")
    os.system("cls")
    Host_name = input("Host>")
    Sec_name = input("Seconds>")
    Method_name = input("Method>")
    Port_name = input("Port>")
    User_name = input("User>")
    time.sleep(1)
    host_data = open(ROOT_DIR + '/data/' + 'host.txt', 'w')
    host_data.write(Host_name)
    host_data.close() 
    sec_data = open(ROOT_DIR + '/data/' + 'sec.txt', 'w')
    sec_data.write(Sec_name)
    sec_data.close() 
    method_data = open(ROOT_DIR + '/data/' + 'method.txt', 'w')
    method_data.write(Sec_name)
    method_data.close() 
    port_data = open(ROOT_DIR + '/data/' + 'port.txt', 'w')
    port_data.write(Port_name)
    port_data.close() 
    user_data = open(ROOT_DIR + '/data/' + 'user.txt', 'w')
    user_data.write(User_name)
    user_data.close()
    os.system("cls")
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(/)", end = "\r")
    time.sleep(0.1)
    print("loading(-)", end = "\r")
    time.sleep(0.1)
    print("loading(\)", end = "\r")
    time.sleep(0.1)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    print("loading(/)", end = "\r")
    time.sleep(0.1)
    print("loading(-)", end = "\r")
    time.sleep(0.1)
    print("loading(\)", end = "\r")
    time.sleep(0.1)
    print("loading(|)", end = "\r")
    time.sleep(0.1)
    os.system("cls")
    input("Installation Complete")

    
    
info()
